name: code-scan

# Controls when the workflow will run
on: [push, pull_request]
  
jobs:


  scan:
    uses: oozou/.github/.github/workflows/code-scan.yaml@main
    with:
        SCAN_TYPE: IAC
        SCAN_INCLUDE: .
    secrets: inherit
